name: Build and Update Dist Branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build artifacts and update dist branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: cachix/install-nix-action@v26
      
      - name: Cache Nix
        uses: cachix/cachix-action@v14
        with:
          name: devenv
      
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Build artifacts
        run: |
          devenv tasks run dist:clean
          devenv tasks run dist:build
      
      - name: Create or update dist branch
        run: |
          # Get current commit hash
          COMMIT_SHA="${GITHUB_SHA}"
          
          # Check if dist branch exists
          if git show-ref --verify --quiet refs/remotes/origin/dist; then
            # If it exists, create a local copy
            git checkout -b dist origin/dist
          else
            # If it doesn't exist, create a new one
            git checkout --orphan dist
          fi
          
          # Copy content from current ref
          git rm -rf .
          git checkout $COMMIT_SHA -- .

          # Remove the original .gitignore and create a minimal one without excluding dist files
          rm -f .gitignore
          cp .dist.gitignore .gitignore
          
          # Add all files
          git add -A
          
          # Commit with source commit hash for reference
          git commit -m "Update dist branch from master (${COMMIT_SHA})" || echo "No changes to commit"
          
          # Push to dist branch
          git push origin dist 